### ISSUE TITLE
Import export interface bug: import/export values cleared after clearing export button.

### ISSUE THREAD

**Issue by abmpicoli** [Religion-And-Revolution-Extended/Mod#16]
https://forums.civfanatics.com/threads/religion-and-revolution-bugs-and-todos.449958/page-120#post-15012865

> I've noticed a bug though which didn't happen before when determining exports and imports. One of the major feature here is the ability to determine limits in imports and exports. As a quick example, let's say we want to export cattle but in always keeping 100 in the city so that it wouldn't decrease production. Similarly, we want to import up to 100 tools in a city so that it could build its stuff, but not more than that.

Well, the issue here is that now, each time we hit the export button, all the data about previously attributed limits is cleared out. This can be rather annoying, as if you don't notice, it will really messes up the whole exchange economy you've carefully built-up. This didn't happen in former versions of the mod.

**Comment by abmpicoli** [comment]
Extra info here https://forums.civfanatics.com/threads/religion-and-revolution-bugs-and-todos.449958/page-120#post-15021751

**Comment by ShadesOT** [comment]
This bug seems resolved, as this does not happen anymore. Clicking on "Export" from the city screen, does not clear the values in the import/export popup.
