### ISSUE TITLE
Test for non-member user creating issues

### ISSUE THREAD

**Issue by albucctestuser** [Religion-And-Revolution-Extended/Mod#99]
This is a test issue created by a non-member user.

**Comment by albucctestuser** [comment]
non-members users can't assign labels, projects or milestones. It is up to team members to properly classify them.

**Comment by albucctestuser** [comment]
A non-member may also close his own ticket.

**Comment by ShadesOT** [comment]
can non-members access the projects page and see and maybe interact with the projects?

**Comment by albucctestuser** [comment]
They can see the project, but not interact with it, of course: it is not their turf to prioritize tickets...

**Comment by albucctestuser** [comment]
Now lets close this to avoid ticket pollution...
